### PR TITLE
set cacheToDisc to false for all xbmcplugin.endOfDirectory calls

### PR DESCRIPTION
**Pull request by invisiblek**
* For whatever reason this needs to be False or you cannot go back
  through the menus

### CODE REVIEW

**Comment by skydrome** [comment]
I suspect your issue is something else, Ive never had an issue going backwards in menus. Plus no other addons ive used had to disable directory listing cache either. If you look at a debug log there might be a clue in it, i hope.
Eliminating anything I might have done to kodi, I tested again on a fresh kodi profile and I can still go backwards (on windows and android).

**Comment by invisiblek** [comment]
Interesting. Haven't tried it on anything except Raspberry Pi, and it definitely seems needed on it. I'll have to get something fired up on a linux box or something and test.

**Comment by skydrome** [comment]
Im going to set it to False since I dont see any differences either way. Its probably better not to write anything to disk if its something with an sdcard like an Rpi or similar anyways.

**Comment by invisiblek** [comment]
FYI if you meant to merge this I think you hit the wrong button :smile:

**Comment by skydrome** [comment]
if this comment sends you a notification or email, can you try out https://github.com/skydrome/LazyMan/releases/download/v1.2.1-rc/plugin.video.lazyman.nhl.tv-1.2.1-rc2.zip

**Pull request closed without merging**
